# Generated by Django 3.1.5 on 2021-02-05 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="user_type",
            field=models.CharField(
                blank=True,
                choices=[("P", "Profesional"), ("G", "Rancher")],
                max_length=1,
                null=True,
            ),
        ),
    ]
