# Generated by Django 3.1.5 on 2021-02-10 16:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("account", "0002_user_user_type"),
    ]

    operations = [
        migrations.RenameField(
            model_name="user",
            old_name="terms_and_condition",
            new_name="terms_and_conditions",
        ),
    ]
